language: cpp

env:
  - CONFIG=Release
  - CONFIG=Debug

compiler: g++

os:
  - linux
  - osx

before_install:
  - sudo apt-get update
  - sudo apt-get install qtcreator qt5-default qttools5-dev-tools g++ libcrypto++-dev
  - lrelease ctSESAM.pro

script:
  - qmake ctSESAM.pro
  - make
  - lrelease ctSESAM.pro

notifications:
  email:
    - travis-ci@ersatzworld.net
