compiler: g++

before_install:
  - sudo apt-get update
  - sudo apt-get install qtcreator qt5-default qttools5-dev-tools g++ libcrypto++-dev
  - lrelease ctSESAM.pro

script:
  - qmake ctSESAM.pro
  - make
  - lrelease ctSESAM.pro
